### ISSUE TITLE
Document timeout

### ISSUE THREAD

**Issue by tomsquest** [nestjs/terminus#123]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

It seems that a global timeout can be configured on Terminus, which the documentation does not tell anything.

Same for the health indicators, there is `promiseTimeout` util function, but it is not documented if one should use it.

## Expected behavior

Explanation of timeouts, recommendation...

## Environment

<pre><code>
Nest version: 5.x
 
For Tooling issues:
- Node version: 10.15.3
- Platform:  Linux

Others:

</code></pre>

**Comment by BrunnerLivio** [comment]
We do not support a global timeout because it wouldn’t make sense in my eyes. Instead the timeout option can be given to individual health indicators as option.
The option parameter is usually the last parameter of a function.

For example the DNSHealthIndicator:

```ts
dns.pingCheck('google', 'https://google.com', { timeout: 800 })
```

The `promiseTimeout` is used for internal stuff, to extend promises with this timeout option, if it is not supported (e.g. DatabaseHealthIndicator uses it when running a SQL check).

I could extend the DNSHealthIndicator example so the users understands that the last parameter  contains these kind of optional options. Would that be sufficient?

**Comment by tomsquest** [comment]
For the documentation problem, yes this would suffice.

But, about design:
Timeout should be the responsibility of the library, not the responsibility of the author of the healthcheck.
Any healtcheck should be timeout protected, and nest-terminus can bring that as the default. This means that developing a new HealthIndicator would only means implementing the actual call (db, smtp...).
