### ISSUE TITLE
Add ApolloHealthIndicator

### ISSUE THREAD

**Issue by cncolder** [nestjs/terminus#156]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Expected behavior

Apollo has a build in health check endpoint: '/.well-known/apollo/server-health'

How to use existed `DNSHealthIndicator` to ping current server? Or add a new `ApolloHealthIndicator`?

See https://www.apollographql.com/docs/apollo-server/features/health-checks

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by BrunnerLivio** [comment]
I am not planning to support Apollo explicitly with terminus, because there is no official support from the NestJS organisation for Apollo. If you are using a third-party NestJS Apollo integration I can have a look on this repository and try to add a `ApolloHealthIndicator` for them.

Nonetheless I think `DNSHealthIndicator` should work fine. For getting the current server address I would recommend to use a `ConfigService` which gets its information using environment variables (`PORT` and `SERVER_ADRESS` for example). In your `terminus-options.service.ts` simply inject your config server and use the `DNSHealthIndicator` to ping the  `${serverAdress}:${port}/.well-known/apollo/server-health`
