### ISSUE TITLE
Swagger compatibility

### ISSUE THREAD

**Issue by mhavelant** [nestjs/terminus#32]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[?] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

There's no documented way for enabling swagger integration for the health endpoints.

## Expected behavior

Documentation for enabling swagger integration for the health endpoints.

## Minimal reproduction of the problem with instructions

-

## What is the motivation / use case for changing the behavior?

I have swagger enabled so I can benefit from the autogenerated documentation for my API. When enabling terminus, its endpoints (e.g /health/readiness) do not show up on the list.

I can add a custom controller with the same endpoint (AppController / @Get('health/readiness') ) and then it is registered and the terminus-code is executed, but that isn't a clean way of doing this.

## Environment

<pre><code>
Nest version: 5.5.0
Nest terminus version: 5.5.2

 
For Tooling issues:
- Node version: v10.15.0  
- Platform: Linux / Docker 

Others:

</code></pre>

**Comment by BrunnerLivio** [comment]
Thank you for reporting!

@kamilmysliwiec 
Terminus does directly modify the underlying http server instance. That is why `@nestjs/swagger` does not recognize the health check routes. 

Also related #33

Some possible thoughts on how we should proceed:

1. Drop the of the underlying `@godaddy/terminus` package and maintain the healtchecks handling ourselves 
  - Pro: Better control how the healthchecks are being implemented (e.g. use internal router API instead of HTTP Server)
  - Pro: No waiting for PR acceptance
  - Contra: Having to maintain it ourselves

2. Create a PR for custom registration of the HTTP listener on `@godaddy/terminus`

I tend to option use option 1. The `@goddady/terminus` lib is really small and the benefit is rather small.

**Comment by BrunnerLivio** [comment]
@mhavelant you're definitely right on that point. I am actually not quite sure how it is going to affect `@godaddy/terminus`.

After some digging, maybe we don't even have to modify `@godaddy/terminus`. I am not quite sure how the internal routes API works in NestJS, but I am currently trying to get it running:

https://github.com/nestjs/terminus/pull/34/files#diff-b93d1fe3b1adefa429e1a750bd1e3abaR137

Maybe @kamilmysliwiec can give me a hint how I should proceed?

**Comment by gperdomor** [comment]
any progress here?

**Comment by cjancsar** [comment]
@BrunnerLivio did you implement a solution?

**Comment by BrunnerLivio** [comment]
It is coming in version 7! Stay tuned :)
![Selection_082](https://user-images.githubusercontent.com/9899423/77259756-0e529f00-6c84-11ea-9761-7c2186389d71.png)
