### ISSUE TITLE
Auto create health controller

### ISSUE THREAD

**Issue by luqezman** [nestjs/terminus#804]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
Current behaviour makes me obligatorily creating the health controller

```typescript
@Controller('health')
export class HealthController {
  constructor(
    private readonly healthCheckService: HealthCheckService,
    private readonly typeOrmHealthIndicator: TypeOrmHealthIndicator,
  ) {}

  @Get()
  async check(): Promise<HealthCheckResult> {
    const health = await this.healthCheckService.check([
      async () => await this.typeOrmHealthIndicator.pingCheck('database'),
    ]);

    return health;
  }
}
```

```typescript
@Module({
  controllers: [HealthController],
  imports: [
    TerminusModule,
    TypeOrmModule.forRoot(ormConfig),
    TypeOrmModule.forFeature([TodoRepository]),
  ],
  ...
})
```

## Expected behavior
To write less code, I would like the health controller to be generated automatically. So, I would just indicate which type of indicator to use(TypeOrmHealthIndicator or other).

## Minimal reproduction of the problem with instructions
There are no problems.

## What is the motivation / use case for changing the behavior?
To practice less code, to make it simple

## Environment

<pre><code>
Nest version: 7.2.0

 
For Tooling issues:
- Node version: v12.16.3 
- Platform:  Windows 

Others:

**Comment by BrunnerLivio** [comment]
The first v6< version of Terminus has an API design that did not require any creation of a controller. [Sample here](https://github.com/nestjs/terminus/blob/62c8394cd173322576f640cc5dcd1356d041143c/sample/deprecated/000-dogs-app/src/health/terminus-options.service.ts#L17-L27). 

Though I've introduced a new design in v7 because with v6 you mostly ended up with such a big and unreadable object. I prefer v7 because its easier testable & is way more transparent for normal NestJS users because it re-uses the functionalities the core framework already offers.

I think the only way I'd see making the current implementation simpler is via a `nest add @nestjs/terminus` schematic which automatically creates your health controller. You will end up with the same code, though you won't need to write it. Would this make sense for you @luqezman ?

**Comment by luqezman** [comment]
@BrunnerLivio in that example you need to create a service, inject dependencies, etc. I want something more easy to implement using default indicators only by configs. Below an example:

 ```
@Module({
  imports: [TerminusModule.forRoot({ endpoint: 'health', healthIndicators: ['database', 'disk', ...] /* Or passing an array of objects here*/)]
})
export class AppModule {}
```

What do you think? Im very lazy guy :)

**Comment by luqezman** [comment]
@BrunnerLivio thanks for the response.

In current behaviour using forRoot, how can I work with TypeOrmHealthIndicator? I didnt know about `forRoot` method.

Everything makes sense for a lazy guy. So, if your approach generates everything for me just passing configs, it makes sense.

**Comment by luqezman** [comment]
@BrunnerLivio I switched to 

```typescript
    TerminusModule.forRootAsync({
      inject: [TypeOrmHealthIndicator],
      useFactory: (
        typeOrmHealthIndicator: TypeOrmHealthIndicator,
      ): TerminusModuleOptions => ({
        endpoints: [
          {
            healthIndicators: [
              async () => await typeOrmHealthIndicator.pingCheck('database'),
            ],
            url: 'health',
          },
        ],
      }),
    })
```

I will suggest something more simple since terminus has base healthIndicators like typeorm, mongoose, etc.


```typescript
    TerminusModule.forRoot({
        endpoints: [
          {
            healthIndicators: [{ name: 'disk', key: 'disk' }, { name: 'typeorm', key: 'database' }],
            url: 'health',
          },
        ],
    })
```

What do you think? I want to avoid code implementation

**Comment by BrunnerLivio** [comment]
@luqezman sorry I kinda lost track of this issue.
I am not too fond of this approach, let me elaborate:

- It's not really extensible. @nestjs/terminus would need to decide what "is" the `'disk'` Health Indicator. I do not feel like that should be the responsibility of the library. If someone wants to use any other disk Health Indicator from a third party contributor, he should be able to use it the same way he/she you'd use the default Health Indicators of @nestjs/terminus.
- What about parameters?
- One of the reasons why I wanted to disregard this kind of model of "big JSON settings object" is that it's not extensible and not really NestJS-like. Using a controller makes much more sense for a NestJS developer because he/she understands the concept behind it. With a JSON object its a magical implementation behind, where you do not have any control over


Nonetheless, I understand your concern about making Health Checks easier. Though I have to be honest; I can't come up with a better system than using schematics at the moment, which feels true to the NestJS approach (easy to get started, extensible, testable, maintainable).

**Comment by BrunnerLivio** [comment]
Closed due to inactivity. Feel free to let me know if you want to re-open
